"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.isAgdaStdlibVersion = exports.isAgdaGitRef = exports.isAgdaVersion = exports.agdaStdlibSdistIndex = exports.agdaBdistIndex = exports.agdaPackageInfoCache = exports.downloadDistIndexEntry = exports.resolveAgdaStdlibVersion = exports.resolveGhcVersion = exports.libraryDir = exports.librariesDir = exports.defaultsFile = exports.librariesFile = exports.installDir = exports.cacheDir = exports.agdaDir = exports.arch = exports.platform = exports.getOptions = exports.needsIcu = exports.supportsClusterCounting = exports.supportsOptimiseHeavily = exports.supportsSplitSections = exports.runPreBuildHook = void 0;
var compat_1 = require("./opts/compat");
Object.defineProperty(exports, "runPreBuildHook", { enumerable: true, get: function () { return compat_1.runPreBuildHook; } });
Object.defineProperty(exports, "supportsSplitSections", { enumerable: true, get: function () { return compat_1.supportsSplitSections; } });
Object.defineProperty(exports, "supportsOptimiseHeavily", { enumerable: true, get: function () { return compat_1.supportsOptimiseHeavily; } });
Object.defineProperty(exports, "supportsClusterCounting", { enumerable: true, get: function () { return compat_1.supportsClusterCounting; } });
Object.defineProperty(exports, "needsIcu", { enumerable: true, get: function () { return compat_1.needsIcu; } });
var get_options_1 = require("./opts/get-options");
Object.defineProperty(exports, "getOptions", { enumerable: true, get: function () { return __importDefault(get_options_1).default; } });
var platform_1 = require("./opts/platform");
Object.defineProperty(exports, "platform", { enumerable: true, get: function () { return platform_1.platform; } });
Object.defineProperty(exports, "arch", { enumerable: true, get: function () { return platform_1.arch; } });
var path_1 = require("./opts/path");
Object.defineProperty(exports, "agdaDir", { enumerable: true, get: function () { return path_1.agdaDir; } });
Object.defineProperty(exports, "cacheDir", { enumerable: true, get: function () { return path_1.cacheDir; } });
Object.defineProperty(exports, "installDir", { enumerable: true, get: function () { return path_1.installDir; } });
Object.defineProperty(exports, "librariesFile", { enumerable: true, get: function () { return path_1.librariesFile; } });
Object.defineProperty(exports, "defaultsFile", { enumerable: true, get: function () { return path_1.defaultsFile; } });
Object.defineProperty(exports, "librariesDir", { enumerable: true, get: function () { return path_1.librariesDir; } });
Object.defineProperty(exports, "libraryDir", { enumerable: true, get: function () { return path_1.libraryDir; } });
var resolve_ghc_version_1 = require("./opts/resolve-ghc-version");
Object.defineProperty(exports, "resolveGhcVersion", { enumerable: true, get: function () { return __importDefault(resolve_ghc_version_1).default; } });
var resolve_agda_stdlib_version_1 = require("./opts/resolve-agda-stdlib-version");
Object.defineProperty(exports, "resolveAgdaStdlibVersion", { enumerable: true, get: function () { return __importDefault(resolve_agda_stdlib_version_1).default; } });
var download_dist_index_entry_1 = require("./opts/download-dist-index-entry");
Object.defineProperty(exports, "downloadDistIndexEntry", { enumerable: true, get: function () { return __importDefault(download_dist_index_entry_1).default; } });
var types_1 = require("./opts/types");
Object.defineProperty(exports, "agdaPackageInfoCache", { enumerable: true, get: function () { return types_1.agdaPackageInfoCache; } });
Object.defineProperty(exports, "agdaBdistIndex", { enumerable: true, get: function () { return types_1.agdaBdistIndex; } });
Object.defineProperty(exports, "agdaStdlibSdistIndex", { enumerable: true, get: function () { return types_1.agdaStdlibSdistIndex; } });
Object.defineProperty(exports, "isAgdaVersion", { enumerable: true, get: function () { return types_1.isAgdaVersion; } });
Object.defineProperty(exports, "isAgdaGitRef", { enumerable: true, get: function () { return types_1.isAgdaGitRef; } });
Object.defineProperty(exports, "isAgdaStdlibVersion", { enumerable: true, get: function () { return types_1.isAgdaStdlibVersion; } });
