#!/usr/bin/env sh

fail="$(mktemp)"

# Build action & cli:
{ npm run all || echo > "$fail"; }
git add src/data/*.json src/data/**/*.json dist/action.js dist/action.js.LEGAL.txt

# Check if any of the previous commands failed:
if [ -s "$fail" ]
then
    rm "$fail"
    exit 1
fi

echo "Run pre-commit"
{ pre-commit run --all-files || echo > "$fail"; }

# Check if any of the previous commands failed:
if [ -s "$fail" ]
then
    rm "$fail"
    exit 1
fi

# Exit successfully
rm "$fail"
exit 0
