export * from './opts/compat'
export {default as getOptions} from './opts/get-options'
export * from './opts/platform'
export * from './opts/path'
export {default as resolveGhcVersion} from './opts/resolve-ghc-version'
export {default as resolveAgdaStdlibVersion} from './opts/resolve-agda-stdlib-version'
export {default as downloadDist} from './opts/download-dist'
export * from './opts/types'
