name: build with cabal

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 1 1 *'
  workflow_call:
  workflow_dispatch:

jobs:
  # Build Agda 2.6.2.2 with Cabal:
  build-2_6_2_2-cabal:
    name: Build Agda (2.6.2.2) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.6.2.2)
        uses: ./
        with:
          agda-version: '2.6.2.2'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
                -cabal{{{stack-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version-match-exact: true
    strategy:
      matrix:
        os: [ubuntu-20.04] # [ubuntu-22.04, macos-11, macos-12, windows-2022]

  # Build Agda 2.6.2.1 with Cabal:
  build-2_6_2_1-cabal:
    name: Build Agda (2.6.2.1) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: setup-yq
        uses: ./.github/actions/setup-yq
      - name: Build Agda (2.6.2.1)
        uses: ./
        with:
          agda-version: '2.6.2'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
                -cabal{{{stack-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version-match-exact: true
    strategy:
      matrix:
        os: [ubuntu-20.04] # [ubuntu-22.04, macos-11, macos-12, windows-2022]

  # Build Agda 2.6.2 with Cabal:
  build-2_6_2-cabal:
    name: Build Agda (2.6.2) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: setup-yq
        uses: ./.github/actions/setup-yq
      - name: Build Agda (2.6.2)
        uses: ./
        with:
          agda-version: '2.6.2'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
                -cabal{{{stack-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version-match-exact: true
    strategy:
      matrix:
        os: [ubuntu-20.04] # [ubuntu-22.04, macos-11, macos-12, windows-2022]

  # Build Agda 2.6.1.3 with Cabal:
  build-2_6_1_3-cabal:
    name: Build Agda (2.6.1.3) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: setup-yq
        uses: ./.github/actions/setup-yq
      - name: Build Agda (2.6.1.3)
        uses: ./
        with:
          agda-version: '2.6.1.3'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
                -cabal{{{stack-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version-match-exact: true
    strategy:
      matrix:
        os: [ubuntu-20.04] # [ubuntu-22.04, macos-11, macos-12, windows-2022]

  # Build Agda 2.6.0.1 with Cabal:
  build-2_6_0_1-cabal:
    name: Build Agda (2.6.0.1) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: setup-yq
        uses: ./.github/actions/setup-yq
      - name: Build Agda (2.6.0.1)
        uses: ./
        with:
          agda-version: '2.6.0.1'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
                -cabal{{{stack-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version-match-exact: true
    strategy:
      matrix:
        os: [ubuntu-20.04] # os: [ubuntu-22.04, macos-11, macos-12]

  # Build Agda 2.5.4.2 with Cabal:
  build-2_5_4_2-cabal:
    name: Build Agda (2.5.4.2) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: setup-yq
        uses: ./.github/actions/setup-yq
      - name: Build Agda (2.5.4.2)
        uses: ./
        with:
          agda-version: '2.5.4.2'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
                -cabal{{{stack-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version-match-exact: true
    strategy:
      matrix:
        os: [ubuntu-20.04] # os: [ubuntu-22.04, macos-11, macos-12]

  # Build Agda 2.5.2 with Cabal:
  build-2_5_2-cabal:
    name: Build Agda (2.5.2) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - id: setup-yq
        uses: ./.github/actions/setup-yq
      - name: Build Agda (2.5.2)
        uses: ./
        with:
          agda-version: '2.5.2'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
                -cabal{{{stack-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version-match-exact: true
    strategy:
      matrix:
        os: [ubuntu-20.04] # os: [ubuntu-22.04, macos-11, macos-12]
