name: release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release-latest:
    name: release latest
    runs-on: ubuntu-latest

    defaults:
      run: { shell: sh }

    steps:
      - uses: actions/checkout@v3
      - name: Update 'latest' tag
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git tag --force latest
          git push --force --tags origin latest
