name: setup agda-stdlib as default

on:
  workflow_call:
  workflow_dispatch:

jobs:
  setup-agda-stdlib-default:
    name: Setup agda-stdlib as default
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Agda
        uses: ./
        with:
          force-no-build: true
          agda-version: 'latest'
          agda-stdlib-version: 'recommended'
          agda-stdlib-default: true
      - name: Test Agda with agda-stdlib as default
        run: |
          agda -v0 hello-world-dep.agda
          agda -v0 hello-world-dep-lookup.agda
          agda -v0 hello-world-proof.agda
        shell: sh
        working-directory: tests/agda-stdlib-default
    strategy:
      matrix:
        os:
          [
            ubuntu-22.04,
            ubuntu-20.04,
            macos-11,
            macos-12,
            windows-2019,
            windows-2022
          ]
