name: setup executables

on:
  workflow_call:
  workflow_dispatch:

jobs:
  setup-echo:
    name: Setup /bin/echo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Agda
        uses: ./
        with:
          force-no-build: true
          agda-version: 'latest'
          agda-executables: |
            /bin/echo
      - name: Test Agda with /bin/echo
        run: |
          agda -v0 echo.agda
        shell: sh
        working-directory: tests/echo
