name: setup libraries

on:
  workflow_call:
  workflow_dispatch:

jobs:
  setup-categories:
    name: Setup agda-categories
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Agda
        uses: ./
        with:
          force-no-build: true
          agda-version: '2.6.2.2'
          agda-stdlib-version: '1.7'
          agda-libraries: |
            https://github.com/agda/agda-categories.git#v0.1.7.1
      - name: Test Agda with agda-categories
        run: |
          agda -v0 hello-categories.agda
        shell: sh
        working-directory: tests/agda-categories
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

  setup-categories-default:
    name: Setup agda-categories as default
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Agda
        uses: ./
        with:
          force-no-build: true
          agda-version: '2.6.2.2'
          agda-stdlib-version: '1.7'
          agda-libraries: |
            https://github.com/agda/agda-categories.git#v0.1.7.1
          agda-defaults: |
            agda-categories
      - name: Test Agda with agda-categories as default
        run: |
          agda -v0 hello-categories.agda
        shell: sh
        working-directory: tests/agda-categories-default
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

  setup-cubical:
    name: Setup cubical
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Agda
        uses: ./
        with:
          force-no-build: true
          agda-version: '2.6.2.2'
          agda-libraries: |
            https://github.com/agda/cubical.git#v0.3
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

  setup-agda-stdlib-default:
    name: Setup agda-stdlib as default
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Agda
        uses: ./
        with:
          force-no-build: true
          agda-version: 'latest'
          agda-stdlib-version: 'recommended'
          agda-defaults: |
            standard-library
      - name: Test Agda with agda-stdlib as default
        run: |
          agda -v0 hello-world-dep.agda
          agda -v0 hello-world-dep-lookup.agda
          agda -v0 hello-world-proof.agda
        shell: sh
        working-directory: tests/agda-stdlib-default
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
